export const USER_REQUEST = 'USER_REQUEST'
export const USER_FETCH = 'USER_FETCH'
export const USER_ADD = 'USER_ADD'
export const USER_DELETE = 'USER_DELETE' 
export const USER_UPDATE = 'USER_UPDATE'
export const USER_ERROR = 'USER_ERROR'